server:
  port: 8092

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      inventory-success: inventory-success
      inventory-fail: inventory-fail
      payment-fail: payment-fail #Caso de erro ele retorna para o payment fazer o rollback
      notify-ending: notify-ending #Para finalizar a saga

    consumer:
      group-id: payment-group
      auto-offset-reset: latest

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:inventory-db}:${DB_PORT:5432}/${DB_NAME:inventory-db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      apache:
        kafka: OFF
