server:
  port: 8090

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      product-validation-start: product-validation-start
      product-validation-fail: product-validation-fail
      payment-success: payment-success #Para publicar para próximo tópico
      notify-ending: notify-ending #Caso ocorra algum erro no product  retorna para OrderService
    consumer:
      group-id: product-validation-group
      auto-offset-reset: latest

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:172.22.79.10}:${DB_PORT:5435}/${DB_NAME:product-db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      apache:
        kafka: OFF